// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyIsD1BYYLv4gQjSOBLjrNfzs4Nno8BH4',
    appId: '1:904955932093:web:00ca41fadce1a754f8f6d4',
    messagingSenderId: '904955932093',
    projectId: 'resto-bill-splitter',
    authDomain: 'resto-bill-splitter.firebaseapp.com',
    storageBucket: 'resto-bill-splitter.appspot.com',
    measurementId: 'G-KL06G5F74Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmADgrNrOj9_Kq5o8uOe3LhjqWFak4jkU',
    appId: '1:904955932093:android:dfaadb2317c6e50af8f6d4',
    messagingSenderId: '904955932093',
    projectId: 'resto-bill-splitter',
    storageBucket: 'resto-bill-splitter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDitoRQRVArB5k1K4pruA0rsIAMOfXVxL0',
    appId: '1:904955932093:ios:4a5ca425afa7837cf8f6d4',
    messagingSenderId: '904955932093',
    projectId: 'resto-bill-splitter',
    storageBucket: 'resto-bill-splitter.appspot.com',
    androidClientId: '904955932093-9n0vk91ijl80qgmemul04bv0ra98d72p.apps.googleusercontent.com',
    iosClientId: '904955932093-jj0nvpnitginr1m83d10g35mcssl7s42.apps.googleusercontent.com',
    iosBundleId: 'com.manolo.restobillsplitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDitoRQRVArB5k1K4pruA0rsIAMOfXVxL0',
    appId: '1:904955932093:ios:4a5ca425afa7837cf8f6d4',
    messagingSenderId: '904955932093',
    projectId: 'resto-bill-splitter',
    storageBucket: 'resto-bill-splitter.appspot.com',
    androidClientId: '904955932093-9n0vk91ijl80qgmemul04bv0ra98d72p.apps.googleusercontent.com',
    iosClientId: '904955932093-jj0nvpnitginr1m83d10g35mcssl7s42.apps.googleusercontent.com',
    iosBundleId: 'com.manolo.restobillsplitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyIsD1BYYLv4gQjSOBLjrNfzs4Nno8BH4',
    appId: '1:904955932093:web:416a600adf17378df8f6d4',
    messagingSenderId: '904955932093',
    projectId: 'resto-bill-splitter',
    authDomain: 'resto-bill-splitter.firebaseapp.com',
    storageBucket: 'resto-bill-splitter.appspot.com',
    measurementId: 'G-0PFPKE7TC5',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDyIsD1BYYLv4gQjSOBLjrNfzs4Nno8BH4',
    appId: '1:904955932093:web:b174773532902cf7f8f6d4',
    messagingSenderId: '904955932093',
    projectId: 'resto-bill-splitter',
    authDomain: 'resto-bill-splitter.firebaseapp.com',
    storageBucket: 'resto-bill-splitter.appspot.com',
    measurementId: 'G-WW0006HMN5',
  );
}
