// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoKlv9Uv-ACA6Pql3Wc974Imuh-mJLyZw',
    appId: '1:149409504095:web:a2f7e2355e36c2d0a534ea',
    messagingSenderId: '149409504095',
    projectId: 'resto-bill-splitter-dev',
    authDomain: 'resto-bill-splitter-dev.firebaseapp.com',
    storageBucket: 'resto-bill-splitter-dev.appspot.com',
    measurementId: 'G-K5HME3FMJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIHjBuKmrs3l4kxzTNmm1d7s9kIyl0wLc',
    appId: '1:149409504095:android:120464ba623be15ba534ea',
    messagingSenderId: '149409504095',
    projectId: 'resto-bill-splitter-dev',
    storageBucket: 'resto-bill-splitter-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRA9oanIMFigiL9eNDNNkvx19poR-DIi0',
    appId: '1:149409504095:ios:c4cc3ed7e4a115cfa534ea',
    messagingSenderId: '149409504095',
    projectId: 'resto-bill-splitter-dev',
    storageBucket: 'resto-bill-splitter-dev.appspot.com',
    iosClientId: '149409504095-2hee30952doqqiofkp4gdare2u2e8eq8.apps.googleusercontent.com',
    iosBundleId: 'com.manolo.restobillsplitter.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRA9oanIMFigiL9eNDNNkvx19poR-DIi0',
    appId: '1:149409504095:ios:c4cc3ed7e4a115cfa534ea',
    messagingSenderId: '149409504095',
    projectId: 'resto-bill-splitter-dev',
    storageBucket: 'resto-bill-splitter-dev.appspot.com',
    iosClientId: '149409504095-2hee30952doqqiofkp4gdare2u2e8eq8.apps.googleusercontent.com',
    iosBundleId: 'com.manolo.restobillsplitter.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoKlv9Uv-ACA6Pql3Wc974Imuh-mJLyZw',
    appId: '1:149409504095:web:bc563d23ef152213a534ea',
    messagingSenderId: '149409504095',
    projectId: 'resto-bill-splitter-dev',
    authDomain: 'resto-bill-splitter-dev.firebaseapp.com',
    storageBucket: 'resto-bill-splitter-dev.appspot.com',
    measurementId: 'G-B3873V2CLG',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCoKlv9Uv-ACA6Pql3Wc974Imuh-mJLyZw',
    appId: '1:149409504095:web:e2b0c56fa70b7f16a534ea',
    messagingSenderId: '149409504095',
    projectId: 'resto-bill-splitter-dev',
    authDomain: 'resto-bill-splitter-dev.firebaseapp.com',
    storageBucket: 'resto-bill-splitter-dev.appspot.com',
    measurementId: 'G-XHZHH24FKZ',
  );
}
